export const labs = [
  {
    id: 'setup-google-account',
    title: 'Set Up Google Account',
    valueProp: 'Install and configure the Google Cloud CLI for project management.',
    timeEffort: '30 min',
    prerequisites: [],
    keyConcepts: ['gcloud CLI', 'Authentication'],
    steps: [],
    track: 'free',
    phaseId: 'foundations',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'easy',
    quizzes: [],
    estimatedCost: '0.00',
    description:
      'Learn how to install and authenticate the gcloud CLI for interacting with GCP services.',
  },
  {
    id: 'deploy-nextjs-cloudrun',
    title: 'Deploy Next.js App to Cloudrun',
    valueProp: 'Package and deploy a Next.js app using Docker and Cloudrun.',
    timeEffort: '90 min',
    prerequisites: ['Set Up gcloud CLI'],
    keyConcepts: ['Cloudrun', 'Docker', 'Next.js'],
    steps: [],
    track: 'free',
    phaseId: 'foundations',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '1.00',
    description: 'Build a minimal Dockerfile and deploy your Next.js chat interface to Cloudrun.',
  },
  {
    id: 'monitoring-logging',
    title: 'Enable Cloud Observability',
    valueProp: 'Set up logging and monitoring for your deployed app.',
    timeEffort: '30 min',
    prerequisites: ['Deploy Next.js App to Cloudrun'],
    keyConcepts: ['Cloud Observability', 'Logging', 'Monitoring'],
    steps: [],
    track: 'free',
    phaseId: 'foundations',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'easy',
    quizzes: [],
    estimatedCost: '0.00',
    description:
      'Configure logging and monitoring to observe your application’s health and performance.',
  },
  {
    id: 'vercel-ai-intro',
    title: 'Interact with Vercel AI',
    valueProp: 'Use Vercel AI for LLM interactions in your app.',
    timeEffort: '45 min',
    prerequisites: ['Deploy Next.js App to Cloudrun'],
    keyConcepts: ['Gemini AI', 'LLM', 'ai SDK'],
    steps: [],
    track: 'free',
    phaseId: 'simple-agent',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '2.00',
    description:
      'Integrate Gemini AI with your application using the Vercel AI SDK for LLM capabilities.',
  },
  {
    id: 'agent-tools',
    title: 'Add Tools to Your Agent',
    valueProp: 'Enhance your LLM agent with external tools and APIs.',
    timeEffort: '45 min',
    prerequisites: ['Deploy Next.js App to Cloudrun', 'Interact with Vercel AI'],
    keyConcepts: ['Gemini AI', 'LLM', 'ai SDK'],
    steps: [],
    track: 'paid',
    phaseId: 'simple-agent',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '2.00',
    description:
      'Learn how to connect external tools and APIs to your LLM agent for enhanced functionality.',
  },
];

export const projects = [
  {
    id: 'serverless-agents-gcp',
    slug: '',
    title: 'Serverless Agents on GCP',
    description: 'Build and deploy serverless applications using Google Cloud Platform services.',
    image: '/assets/images/projects/serverless-agents-gcp.png',
    tags: ['GCP', 'Serverless', 'Cloudrun', 'AI', 'Agents', 'Next.js'],
    timeEffort: '4-6 hours',
    difficulty: 'medium',
    phaseIds: ['foundations', 'agent-setup', 'advanced-agent', 'secure-agent'],
    labs: labs,
    roadmapId: 'serverless-agents-gcp',
    prerequisites: [
      'Basic understanding of cloud computing concepts.',
      'Familiarity with JavaScript/TypeScript.',
      'Basic knowledge of Docker and containerization.',
    ],
    outcomes: [
      'Set up and configure Google Cloud CLI.',
      'Deploy a Next.js application to Google Cloudrun using Docker.',
      'Integrate AI SDK for LLM agent functionality within the application.',
      'Implement logging and monitoring using Google Cloud Observability tools.',
    ],
  },
];
