export const labs = [
  {
    id: 'setup-google-account',
    title: 'Set Up Google Account',
    valueProp: 'Install and configure the Google Cloud CLI for project management.',
    timeEffort: '30 min',
    prerequisites: [],
    keyConcepts: ['gcloud CLI', 'Authentication'],
    steps: [],
    track: 'free',
    phaseId: 'foundations',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'easy',
    quizzes: [],
    estimatedCost: '0.00',
    description:
      'Learn how to install and authenticate the gcloud CLI for interacting with GCP services.',
  },
  {
    id: 'deploy-nextjs-cloudrun',
    title: 'Deploy Next.js App to Cloudrun',
    valueProp: 'Package and deploy a Next.js app using Docker and Cloudrun.',
    timeEffort: '90 min',
    prerequisites: ['Set Up gcloud CLI'],
    keyConcepts: ['Cloudrun', 'Docker', 'Next.js'],
    steps: [],
    track: 'free',
    phaseId: 'foundations',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '1.00',
    description: 'Build a minimal Dockerfile and deploy your Next.js chat interface to Cloudrun.',
  },
  {
    id: 'monitoring-logging',
    title: 'Enable Cloud Observability',
    valueProp: 'Set up logging and monitoring for your deployed app.',
    timeEffort: '30 min',
    prerequisites: ['Deploy Next.js App to Cloudrun'],
    keyConcepts: ['Cloud Observability', 'Logging', 'Monitoring'],
    steps: [],
    track: 'free',
    phaseId: 'foundations',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'easy',
    quizzes: [],
    estimatedCost: '0.00',
    description:
      'Configure logging and monitoring to observe your application’s health and performance.',
  },
  {
    id: 'vercel-ai-intro',
    title: 'Interact with Vercel AI',
    valueProp: 'Use Vercel AI for LLM interactions in your app.',
    timeEffort: '45 min',
    prerequisites: ['Deploy Next.js App to Cloudrun'],
    keyConcepts: ['Gemini AI', 'LLM', 'ai SDK'],
    steps: [],
    track: 'free',
    phaseId: 'basic-agent',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '2.00',
    description:
      'Integrate Gemini AI with your application using the Vercel AI SDK for LLM capabilities.',
  },
  {
    id: 'agent-tools',
    title: 'Add Tools to Your Agent',
    valueProp: 'Enhance your LLM agent with external tools and APIs.',
    timeEffort: '45 min',
    prerequisites: ['Deploy Next.js App to Cloudrun', 'Interact with Vercel AI'],
    keyConcepts: ['Gemini AI', 'LLM', 'ai SDK'],
    steps: [],
    track: 'paid',
    phaseId: 'basic-agent',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '2.00',
    description:
      'Learn how to connect external tools and APIs to your LLM agent for enhanced functionality.',
  },
  {
    id: 'conversation-memory',
    title: 'Conversation Memory',
    valueProp: 'Enable your agent to remember previous messages and context.',
    timeEffort: '30 min',
    prerequisites: ['Add Tools to Your Agent'],
    keyConcepts: ['Memory', 'Session State', 'Context'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-memory',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Implement memory so your agent can reference earlier parts of the conversation.',
  },
  {
    id: 'persist-sessions',
    title: 'Persist Sessions',
    valueProp: 'Store and retrieve user sessions for long-term memory.',
    timeEffort: '30 min',
    prerequisites: ['Conversation Memory'],
    keyConcepts: ['Persistence', 'Sessions', 'Databases'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-memory',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Save and load user sessions to give your agent long-term memory.',
  },
  {
    id: 'agent-tools',
    title: 'Agent Tools',
    valueProp: 'Integrate external tools for your agent to use.',
    timeEffort: '45 min',
    prerequisites: ['Persist Sessions'],
    keyConcepts: ['Tools', 'APIs', 'Integration'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-tools',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '1.00',
    description: 'Connect your agent to external APIs and tools for enhanced capabilities.',
  },
  {
    id: 'order-tool',
    title: 'Order Tool',
    valueProp: 'Build a tool that lets your agent place and track orders.',
    timeEffort: '30 min',
    prerequisites: ['Agent Tools'],
    keyConcepts: ['Order Management', 'APIs'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-tools',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Create a custom tool for your agent to handle order-related tasks.',
  },
  {
    id: 'rag-tool',
    title: 'RAG Tool',
    valueProp: 'Add Retrieval-Augmented Generation (RAG) to your agent.',
    timeEffort: '45 min',
    prerequisites: ['Order Tool'],
    keyConcepts: ['RAG', 'Retrieval', 'Knowledge Base'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-tools',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'hard',
    quizzes: [],
    estimatedCost: '1.00',
    description: 'Enable your agent to retrieve and use external knowledge for better answers.',
  },
  {
    id: 'render-tools-responses',
    title: 'Render Tools Responses',
    valueProp: 'Display tool results in your agent UI.',
    timeEffort: '30 min',
    prerequisites: ['RAG Tool'],
    keyConcepts: ['UI', 'Rendering', 'Tool Output'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-tools',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Show results from agent tools in your application interface.',
  },
  {
    id: 'setup-auth',
    title: 'Setup Auth',
    valueProp: 'Add authentication to secure your agent and user data.',
    timeEffort: '30 min',
    prerequisites: ['Evals'],
    keyConcepts: ['Authentication', 'Security'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-security',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Implement authentication to protect your agent and restrict access.',
  },
  {
    id: 'user-context-rbac',
    title: 'User Context & RBAC',
    valueProp: 'Support user context and role-based access control (RBAC).',
    timeEffort: '30 min',
    prerequisites: ['Setup Auth'],
    keyConcepts: ['RBAC', 'User Context', 'Authorization'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-security',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Add user context and implement RBAC to control agent actions.',
  },
  {
    id: 'rate-limiting',
    title: 'Rate Limiting',
    valueProp: 'Protect your agent from abuse with rate limiting.',
    timeEffort: '30 min',
    prerequisites: ['User Context & RBAC'],
    keyConcepts: ['Rate Limiting', 'Security', 'API Protection'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-security',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.25',
    description: 'Implement rate limiting to prevent abuse and ensure fair usage.',
  },
  {
    id: 'error-handling',
    title: 'Error Handling',
    valueProp: 'Add robust error handling to your agent.',
    timeEffort: '30 min',
    prerequisites: ['Rate Limiting'],
    keyConcepts: ['Error Handling', 'Resilience'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-security',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.25',
    description: 'Ensure your agent can gracefully handle and report errors.',
  },
  {
    id: 'guardrails',
    title: 'Guardrails',
    valueProp: 'Add guardrails to keep your agent safe and on-task.',
    timeEffort: '30 min',
    prerequisites: ['Error Handling'],
    keyConcepts: ['Guardrails', 'Safety', 'Validation'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-security',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Implement validation and safety checks to keep your agent secure.',
  },
  {
    id: 'langfuse',
    title: 'Langfuse',
    valueProp: 'Integrate Langfuse for advanced agent analytics.',
    timeEffort: '30 min',
    prerequisites: ['Observability'],
    keyConcepts: ['Langfuse', 'Analytics', 'Tracing'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-observability',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Use Langfuse to analyze and trace your agent’s actions and performance.',
  },
  {
    id: 'evals',
    title: 'Evals',
    valueProp: 'Evaluate your agent’s performance and accuracy.',
    timeEffort: '30 min',
    prerequisites: ['UI Polish'],
    keyConcepts: ['Evaluation', 'Testing', 'Metrics'],
    steps: [],
    track: 'paid',
    phaseId: 'agent-observability',
    roadmapId: 'serverless-agents-gcp',
    difficulty: 'medium',
    quizzes: [],
    estimatedCost: '0.50',
    description: 'Test and measure your agent’s capabilities and output.',
  },
];

export const projects = [
  {
    id: 'serverless-agents-gcp',
    slug: '',
    title: 'Serverless Agents on GCP',
    description: 'Build and deploy serverless applications using Google Cloud Platform services.',
    image: '/assets/images/projects/serverless-agents-gcp.png',
    tags: ['GCP', 'Serverless', 'Cloudrun', 'AI', 'Agents', 'Next.js'],
    timeEffort: '4-6 hours',
    difficulty: 'medium',
    phaseIds: ['foundations', 'agent-setup', 'advanced-agent', 'agent-security'],
    labs: labs,
    roadmapId: 'serverless-agents-gcp',
    prerequisites: [
      'Basic understanding of cloud computing concepts.',
      'Familiarity with JavaScript/TypeScript.',
      'Basic knowledge of Docker and containerization.',
    ],
    outcomes: [
      'Set up and configure Google Cloud CLI.',
      'Deploy a Next.js application to Google Cloudrun using Docker.',
      'Integrate AI SDK for LLM agent functionality within the application.',
      'Implement logging and monitoring using Google Cloud Observability tools.',
    ],
  },
];
